
server:
  port: 80

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} : %msg%n"
  level:
    com.core.webhook: DEBUG

spring:
  application:
    name: core-webhook
  cloud:
    openfeign:
      client:
        config:
          mercadoPago:
            url: https://api.mercadopago.com
            connectTimeout: 5000
            readTimeout: 10000
            loggerLevel: FULL
          default:
            connectTimeout: 5000
            readTimeout: 10000
            loggerLevel: FULL

  # 1. Datasource Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/payments?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 2. JPA/Hibernate Configuration
  jpa:
    show-sql: true # Log SQL statements
    hibernate:
      ddl-auto: none # Options: none, update, create, create-drop, validate
    properties:
      hibernate:
        # Specifies the MySQL Dialect for Hibernate
        dialect: org.hibernate.dialect.MySQLDialect